var useState=React.useState,useEffect=React.useEffect,useCallback=React.useCallback,useMemo=React.useMemo;
var SUPA_URL="https://qcczcyqtflvxhewvucxn.supabase.co";
var SUPA_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjY3pjeXF0Zmx2eGhld3Z1Y3huIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA5NTM2NzcsImV4cCI6MjA5NjUyOTY3N30.R6qWoi6ZmWaGQ2x1j6xiE7AzCySmFfQZY0Wg77a91Pc";
var KEYS={users:"vc_users",pets:"vc_pets",records:"vc_records",session:"vc_session",appts:"vc_appointments",notifs:"vc_notifications",blocked:"vc_blocked_days",reqs:"vc_appt_requests"};
function supaH(){return{"Content-Type":"application/json","apikey":SUPA_KEY,"Authorization":"Bearer "+SUPA_KEY,"Prefer":"return=representation"};}
function mapUser(r){ if(!r)return null; return {id:r.id,role:r.role,firstName:r.first_name,lastName:r.last_name,email:r.email,password:r.password,docType:r.doc_type||"DNI",docNum:r.doc_num||"",phone:r.phone||"",address:r.address||"",blocked:r.blocked||false}; }
function userToDb(u){ return {id:u.id,role:u.role,first_name:u.firstName||"",last_name:u.lastName||"",email:u.email,password:u.password,doc_type:u.docType||"DNI",doc_num:u.docNum||"",phone:u.phone||"",address:u.address||"",blocked:u.blocked||false}; }
function mapPet(r){ if(!r)return null; return {id:r.id,ownerId:r.owner_id,name:r.name,species:r.species||"Perro",breed:r.breed||"",sex:r.sex||"Macho",dob:r.dob||"",weight:r.weight||"",color:r.color||"",avatar:r.avatar||"🐾",photo:r.photo||""}; }
function petToDb(p){ return {id:p.id,owner_id:p.ownerId||p.owner_id,name:p.name,species:p.species||"Perro",breed:p.breed||"",sex:p.sex||"Macho",dob:p.dob||"",weight:p.weight||"",color:p.color||"",avatar:p.avatar||"🐾",photo:p.photo||""}; }
function mapRecord(r){ if(!r)return null; return {id:r.id,petId:r.pet_id,vetId:r.vet_id,date:r.date,type:r.type||"Consulta",diagnosis:r.diagnosis||"",treatment:r.treatment||"",notes:r.notes||"",nextVisit:r.next_visit||"",weight:r.weight||"",attended:r.attended,duration:r.duration,items:r.items||[]}; }
function recordToDb(r){ return {id:r.id,pet_id:r.petId||r.pet_id,vet_id:r.vetId||r.vet_id,date:r.date,type:r.type||"Consulta",diagnosis:r.diagnosis||"",treatment:r.treatment||"",notes:r.notes||"",next_visit:r.nextVisit||"",weight:r.weight||"",attended:r.attended!=null?r.attended:null,duration:r.duration||null,items:r.items||[]}; }
function mapAppt(r){ if(!r)return null; return {id:r.id,petId:r.pet_id,ownerId:r.owner_id,vetId:r.vet_id,date:r.date,time:r.time,type:r.type||"Consulta",notes:r.notes||"",status:r.status||"pending",attended:r.attended}; }
function apptToDb(a){ return {id:a.id,pet_id:a.petId||a.pet_id,owner_id:a.ownerId||a.owner_id,vet_id:a.vetId||a.vet_id,date:a.date,time:a.time,type:a.type||"Consulta",notes:a.notes||"",status:a.status||"pending",attended:a.attended!=null?a.attended:null}; }
function mapReq(r){ if(!r)return null; return {id:r.id,petId:r.pet_id,ownerId:r.owner_id,vetId:r.vet_id,date:r.date,time:r.time,type:r.type||"Consulta",notes:r.notes||"",status:r.status||"pending",ts:r.ts||Date.now()}; }
function reqToDb(q){ return {id:q.id,pet_id:q.petId||q.pet_id,owner_id:q.ownerId||q.owner_id,vet_id:q.vetId||q.vet_id,date:q.date,time:q.time,type:q.type||"Consulta",notes:q.notes||"",status:q.status||"pending",ts:q.ts||Date.now()}; }
function mapNotif(r){ if(!r)return null; return {id:r.id,toId:r.to_id,msg:r.msg,icon:r.icon||"🔔",actionId:r.action_id||"",read:r.read||false,ts:r.ts||Date.now()}; }
function notifToDb(n){ return {id:n.id,to_id:n.toId||n.to_id,msg:n.msg,icon:n.icon||"🔔",action_id:n.actionId||"",read:n.read||false,ts:n.ts||Date.now()}; }
function mapBlocked(r){ return {date:r.date,reason:r.reason||"No disponible"}; }
async function sbAll(t){try{var r=await fetch(SUPA_URL+"/rest/v1/"+t+"?select=*&order=created_at.asc",{headers:supaH()});return r.ok?await r.json():[];}catch(e){return[];}}
async function sbUpsertMany(t,rows){try{var r=await fetch(SUPA_URL+"/rest/v1/"+t+"?on_conflict=id",{method:"POST",headers:Object.assign({},supaH(),{"Prefer":"resolution=merge-duplicates,return=representation"}),body:JSON.stringify(rows)});return r.ok;}catch(e){return false;}}
async function sbPatch(t,id,data){try{var r=await fetch(SUPA_URL+"/rest/v1/"+t+"?id=eq."+id,{method:"PATCH",headers:supaH(),body:JSON.stringify(data)});return r.ok;}catch(e){return false;}}
async function sbDel(t,id){try{var r=await fetch(SUPA_URL+"/rest/v1/"+t+"?id=eq."+id,{method:"DELETE",headers:supaH()});return r.ok;}catch(e){return false;}}
async function sbDelWhere(t,col,val){try{var r=await fetch(SUPA_URL+"/rest/v1/"+t+"?"+col+"=eq."+encodeURIComponent(val),{method:"DELETE",headers:supaH()});return r.ok;}catch(e){return false;}}
async function sGet(k){try{if(k===KEYS.session){return localStorage.getItem("vc_session")||null;}if(k===KEYS.users){var ru=await sbAll("vc_users");return ru&&ru.length?ru.map(mapUser):null;}if(k===KEYS.pets){var rp=await sbAll("vc_pets");return rp&&rp.length?rp.map(mapPet):null;}if(k===KEYS.records){var rr=await sbAll("vc_records");return rr&&rr.length?rr.map(mapRecord):[];}if(k===KEYS.appts){var ra=await sbAll("vc_appointments");return ra&&ra.length?ra.map(mapAppt):[];}if(k===KEYS.reqs){var rq=await sbAll("vc_appt_requests");return rq&&rq.length?rq.map(mapReq):[];}if(k===KEYS.notifs){var rn=await sbAll("vc_notifications");return rn&&rn.length?rn.map(mapNotif):[];}if(k===KEYS.blocked){var rb=await sbAll("vc_blocked_days");return rb&&rb.length?rb.map(mapBlocked):[];}return null;}catch(e){return null;}}
async function sSet(k,v){try{if(k===KEYS.session){if(v===null||v==="null")localStorage.removeItem("vc_session");else localStorage.setItem("vc_session",v);return;}if(!Array.isArray(v))return;if(k===KEYS.users){await sbUpsertMany("vc_users",v.map(userToDb));return;}if(k===KEYS.pets){await sbUpsertMany("vc_pets",v.map(petToDb));return;}if(k===KEYS.records){await sbUpsertMany("vc_records",v.map(recordToDb));return;}if(k===KEYS.appts){await sbUpsertMany("vc_appointments",v.map(apptToDb));return;}if(k===KEYS.reqs){await sbUpsertMany("vc_appt_requests",v.map(reqToDb));return;}if(k===KEYS.notifs){await sbUpsertMany("vc_notifications",v.map(notifToDb));return;}if(k===KEYS.blocked){await sbUpsertMany("vc_blocked_days",v.map(mapBlocked));return;}}catch(e){}}
var BREEDS={Perro:["Beagle","Border Collie","Boxer","Bulldog Francés","Caniche","Chihuahua","Dálmata","Doberman","Golden Retriever","Husky Siberiano","Labrador Retriever","Mestizo","Pastor Alemán","Rottweiler","Shih Tzu","Yorkshire Terrier","Gran Danés","Pomerania"],Gato:["Angora Turco","Azul Ruso","Bengalí","British Shorthair","Maine Coon","Mestizo","Persa","Ragdoll","Scottish Fold","Siamés","Siberiano"],Ave:["Agapornis","Cacatúa","Canario","Guacamayo","Loro","Ninfa","Periquito"],Conejo:["Angora","Belier","Mini Rex","New Zealand","Rex"],Reptil:["Bearded Dragon","Gecko Leopardo","Iguana Verde","Tortuga de Tierra"],Pez:["Betta","Goldfish","Guppy","Neon Tetra"],Otro:["Cobayo","Erizo","Hurón","Rata"]};
var SEED_USERS=[{id:"u0",role:"admin",firstName:"Admin",lastName:"VetCare",email:"admin@vetcare.com",password:"admin2025",docType:"DNI",docNum:"00000001",blocked:false,phone:"",address:""},{id:"u1",role:"vet",firstName:"German",lastName:"Cabrera",email:"german@clinica.com",password:"vetcare2025",docType:"DNI",docNum:"12345678",blocked:false,phone:"",address:""},{id:"u2",role:"owner",firstName:"Carlos",lastName:"Ruiz",email:"carlos@mail.com",password:"1234",docType:"DNI",docNum:"87654321",blocked:false,phone:"999111222",address:"Av. Lima 123"},{id:"u3",role:"owner",firstName:"Ana",lastName:"Torres",email:"ana@mail.com",password:"1234",docType:"DNI",docNum:"11223344",blocked:false,phone:"999333444",address:""},{id:"u4",role:"owner",firstName:"Miguel",lastName:"Fernandez",email:"miguel@mail.com",password:"1234",docType:"DNI",docNum:"22334455",blocked:false,phone:"999222333",address:""},{id:"u5",role:"owner",firstName:"Lucia",lastName:"Gomez",email:"lucia@mail.com",password:"1234",docType:"DNI",docNum:"33445566",blocked:false,phone:"999333555",address:""},{id:"u6",role:"owner",firstName:"Roberto",lastName:"Sanchez",email:"roberto@mail.com",password:"1234",docType:"DNI",docNum:"44556677",blocked:false,phone:"999444666",address:""},{id:"u7",role:"owner",firstName:"Patricia",lastName:"Lopez",email:"patricia@mail.com",password:"1234",docType:"DNI",docNum:"55667788",blocked:false,phone:"999555777",address:""},{id:"u8",role:"owner",firstName:"Jorge",lastName:"Martinez",email:"jorge@mail.com",password:"1234",docType:"DNI",docNum:"66778899",blocked:false,phone:"999666888",address:""},{id:"u9",role:"owner",firstName:"Sofia",lastName:"Diaz",email:"sofia@mail.com",password:"1234",docType:"DNI",docNum:"77889900",blocked:false,phone:"999777999",address:""}];
var SEED_PETS=[{id:"p1",ownerId:"u2",name:"Mochi",species:"Gato",breed:"Siames",sex:"Hembra",dob:"2020-03-15",weight:"4.2",color:"Crema y marron",avatar:"🐱",photo:""},{id:"p2",ownerId:"u2",name:"Rocky",species:"Perro",breed:"Labrador Retriever",sex:"Macho",dob:"2018-07-22",weight:"28.5",color:"Amarillo",avatar:"🐶",photo:""},{id:"p3",ownerId:"u3",name:"Luna",species:"Perro",breed:"Caniche",sex:"Hembra",dob:"2021-11-05",weight:"8.1",color:"Blanco",avatar:"🐩",photo:""},{id:"p4",ownerId:"u4",name:"Max",species:"Perro",breed:"Golden Retriever",sex:"Macho",dob:"2019-05-10",weight:"32.0",color:"Dorado",avatar:"🐶",photo:""},{id:"p5",ownerId:"u5",name:"Coco",species:"Gato",breed:"Persa",sex:"Hembra",dob:"2022-02-14",weight:"3.8",color:"Blanco",avatar:"🐱",photo:""},{id:"p6",ownerId:"u6",name:"Bruno",species:"Perro",breed:"Pastor Aleman",sex:"Macho",dob:"2017-09-01",weight:"38.0",color:"Negro y marron",avatar:"🐶",photo:""},{id:"p7",ownerId:"u7",name:"Nala",species:"Gato",breed:"British Shorthair",sex:"Hembra",dob:"2021-06-20",weight:"4.5",color:"Gris",avatar:"🐱",photo:""},{id:"p8",ownerId:"u8",name:"Toby",species:"Perro",breed:"Beagle",sex:"Macho",dob:"2020-11-30",weight:"12.5",color:"Tricolor",avatar:"🐶",photo:""},{id:"p9",ownerId:"u9",name:"Princesa",species:"Gato",breed:"Ragdoll",sex:"Hembra",dob:"2023-01-08",weight:"3.2",color:"Gris y blanco",avatar:"🐱",photo:""}];
var SEED_RECORDS=[{id:"r1",petId:"p1",vetId:"u1",date:"2024-10-12",type:"Consulta",diagnosis:"Dermatitis leve",treatment:"Crema hidrocortisona 7 dias",notes:"Prurito dorsal",nextVisit:"2026-06-15",weight:"4.1",attended:true,duration:20,items:[]},{id:"r2",petId:"p1",vetId:"u1",date:"2025-01-08",type:"Vacunación",diagnosis:"Control anual",treatment:"Vacuna triple felina",notes:"Sin reacciones",nextVisit:"2026-06-20",weight:"4.2",attended:true,duration:15,items:[]},{id:"r3",petId:"p2",vetId:"u1",date:"2025-03-20",type:"Cirugía",diagnosis:"Displasia de cadera leve",treatment:"Fisioterapia + meloxicam",notes:"Buena recuperacion",nextVisit:"2026-06-25",weight:"28.5",attended:true,duration:45,items:[]},{id:"r4",petId:"p3",vetId:"u1",date:"2025-05-02",type:"Consulta",diagnosis:"Otitis externa",treatment:"Gotas Otomax 10 dias",notes:"Limpieza auditiva",nextVisit:"2026-07-01",weight:"8.0",attended:false,duration:null,items:[]}];
var SEED_APPTS=[{id:"a1",petId:"p1",ownerId:"u2",vetId:"u1",date:"2026-06-15",time:"09:00",type:"Vacunación",notes:"Control anual",status:"confirmed",attended:null},{id:"a2",petId:"p2",ownerId:"u2",vetId:"u1",date:"2026-06-20",time:"10:30",type:"Control",notes:"Revisión displasia",status:"pending",attended:null},{id:"a3",petId:"p3",ownerId:"u3",vetId:"u1",date:"2026-06-25",time:"11:00",type:"Consulta",notes:"Seguimiento otitis",status:"pending",attended:null},{id:"da0",petId:"p4",ownerId:"u4",vetId:"u1",date:"2026-07-08",time:"08:00",type:"Consulta",notes:"Control rutina",status:"confirmed",attended:null},{id:"da1",petId:"p5",ownerId:"u5",vetId:"u1",date:"2026-07-09",time:"09:30",type:"Vacunación",notes:"Revisión general",status:"confirmed",attended:null},{id:"da2",petId:"p6",ownerId:"u6",vetId:"u1",date:"2026-07-10",time:"10:00",type:"Control",notes:"Seguimiento",status:"confirmed",attended:null},{id:"da3",petId:"p7",ownerId:"u7",vetId:"u1",date:"2026-07-11",time:"11:30",type:"Consulta",notes:"Rutina",status:"confirmed",attended:null},{id:"da4",petId:"p8",ownerId:"u8",vetId:"u1",date:"2026-07-12",time:"12:00",type:"Control",notes:"Seguimiento",status:"confirmed",attended:null},{id:"da5",petId:"p9",ownerId:"u9",vetId:"u1",date:"2026-07-13",time:"08:30",type:"Consulta",notes:"Control rutina",status:"confirmed",attended:null},{id:"da6",petId:"p1",ownerId:"u2",vetId:"u1",date:"2026-07-14",time:"09:00",type:"Vacunación",notes:"Anual",status:"confirmed",attended:null}];
var SEED_REQS=[{id:"rq0",petId:"p1",ownerId:"u2",date:"2026-07-15",time:"09:00",type:"Consulta",notes:"Revisión rutina",status:"pending",ts:1749000000},{id:"rq1",petId:"p2",ownerId:"u3",date:"2026-07-15",time:"10:00",type:"Control",notes:"Seguimiento",status:"pending",ts:1749001000},{id:"rq2",petId:"p3",ownerId:"u4",date:"2026-07-16",time:"09:00",type:"Vacunación",notes:"Vacuna anual",status:"pending",ts:1749002000},{id:"rq3",petId:"p4",ownerId:"u5",date:"2026-07-16",time:"10:00",type:"Consulta",notes:"Primera visita",status:"pending",ts:1749003000},{id:"rq4",petId:"p5",ownerId:"u6",date:"2026-07-17",time:"08:00",type:"Control",notes:"Rutina",status:"pending",ts:1749004000},{id:"rq5",petId:"p6",ownerId:"u7",date:"2026-07-17",time:"09:30",type:"Consulta",notes:"Revisión",status:"pending",ts:1749005000},{id:"rq6",petId:"p7",ownerId:"u8",date:"2026-07-18",time:"10:00",type:"Vacunación",notes:"Control anual",status:"pending",ts:1749006000},{id:"rq7",petId:"p8",ownerId:"u9",date:"2026-07-18",time:"11:00",type:"Consulta",notes:"Primer control",status:"pending",ts:1749007000}];
function fullName(u){if(!u)return"—";if(u.firstName&&u.lastName)return u.firstName+" "+u.lastName;return u.firstName||u.lastName||u.name||"—";}
function fmtDate(iso){if(!iso)return"—";var p=iso.split("-");return p[2]+"-"+p[1]+"-"+p[0];}
function today(){return new Date().toISOString().slice(0,10);}
function genId(){return Math.random().toString(36).slice(2,10);}
function toBase64(f){return new Promise(function(r,j){var fr=new FileReader();fr.onload=function(){r(fr.result);};fr.onerror=j;fr.readAsDataURL(f);});}
function calcAge(dob){if(!dob)return null;var mo=(new Date().getFullYear()-new Date(dob).getFullYear())*12+new Date().getMonth()-new Date(dob).getMonth();if(mo<1)return"recién nacido";if(mo<12)return mo+" mes"+(mo>1?"es":"");var y=Math.floor(mo/12),m=mo%12;return m>0?y+" año"+(y>1?"s":"")+" y "+m+" mes"+(m>1?"es":""):y+" año"+(y>1?"s":"");}
function sanitizePhone(v){return v.replace(/\D/g,"").slice(0,9);}
function validateDoc(type,num){if(!num)return"Numero obligatorio.";if(type==="DNI"){if(!/^\d{8}$/.test(num))return"DNI: 8 digitos exactos.";}else{if(!/^[A-Z]\d{8}$/.test(num))return"Formato: letra + 8 digitos.";}return"";}
var TIME_SLOTS=[];for(var _h=8;_h<19;_h++){for(var _m=0;_m<60;_m+=30){TIME_SLOTS.push((_h<10?"0":"")+_h+":"+(_m===0?"00":"30"));}}
function useDark(){
  var mq=typeof window!=="undefined"?window.matchMedia("(prefers-color-scheme: dark)"):{matches:false};
  var d=useState(mq.matches); var dark=d[0],setDark=d[1];
  useEffect(function(){
    var handler=function(e){setDark(e.matches);};
    mq.addEventListener("change",handler);
    return function(){mq.removeEventListener("change",handler);};
  },[]);
  return dark;
}
function useIsMobile(){
  var s=useState(window.innerWidth<720); var mob=s[0],setMob=s[1];
  useEffect(function(){
    var h=function(){setMob(window.innerWidth<720);};
    window.addEventListener("resize",h);
    return function(){window.removeEventListener("resize",h);};
  },[]);
  return mob;
}
function useToast(){
  var s=useState([]); var toasts=s[0]; var setToasts=s[1];
  var push=useCallback(function(msg,type){
    type=type||"success"; var id=genId();
    setToasts(function(t){return t.concat([{id:id,msg:msg,type:type}]);});
    setTimeout(function(){setToasts(function(t){return t.filter(function(x){return x.id!==id;});});},3800);
  },[]);
  return {toasts:toasts,push:push};
}
function byId(arr,id){for(var _i=0;_i<arr.length;_i++){if(arr[_i].id===id)return arr[_i];}return null;}
var sOverflow={overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"};
function byField(arr,field,val){for(var _i=0;_i<arr.length;_i++){if(arr[_i][field]===val)return arr[_i];}return null;}
function palette(dark){return{cream:dark?"#111827":"#F0F4F8",peach:dark?"#1E2A3A":"#E2EAF4",tan:dark?"#2D4A6B":"#B8CFE8",brown:dark?"#4DB8C8":"#1E7A8C",brownDark:dark?"#7DD4E0":"#145A6A",green:dark?"#34C98A":"#0D9B6A",greenLight:dark?"#0A2E1E":"#D1F5E8",blue:dark?"#60B4E8":"#2E86C1",blueLight:dark?"#0A1D2E":"#D6EAF8",red:dark?"#F07070":"#E05252",redLight:dark?"#2E1010":"#FDEAEA",yellow:dark?"#F5C842":"#D4900A",yellowLight:dark?"#2A1E00":"#FFF3CD",purple:dark?"#A880E0":"#7B4FCC",purpleLight:dark?"#1A1030":"#EDE6FA",text:dark?"#E8F0F8":"#1A2B3C",textMid:dark?"#8AABB8":"#4A6275",textLight:dark?"#4A6882":"#8BA4B5",surface:dark?"#1A2535":"#FFFFFF",border:dark?"#2A3F58":"#CBD8E4",topbar:dark?"#0D1929":"#1A3A5C",sidebar:dark?"#0D1929":"#1A3A5C",navIcon:dark?"#7DD4E0":"#FFFFFF",navIconDim:dark?"#4A6882":"rgba(255,255,255,0.55)",brown_alpha:dark?"rgba(77,184,200,0.25)":"rgba(30,122,140,0.25)"};}
var buildCss=function(C){return"*{box-sizing:border-box;margin:0;padding:0;}html{font-size:16px;}body{font-family:'Nunito',sans-serif;background:"+C.cream+";color:"+C.text+";-webkit-text-size-adjust:100%;}\n::-webkit-scrollbar{width:5px;}::-webkit-scrollbar-track{background:"+C.peach+";}::-webkit-scrollbar-thumb{background:"+C.tan+";border-radius:3px;}\ninput,select,textarea{font-family:'Nunito',sans-serif;border:1.5px solid "+C.border+";border-radius:10px;padding:11px 14px;background:"+C.surface+";color:"+C.text+";width:100%;font-size:16px;outline:none;transition:border-color .2s;-webkit-appearance:none;appearance:none;}\ninput:focus,select:focus,textarea:focus{border-color:"+C.brown+";box-shadow:0 0 0 3px "+C.brown+"33;}\ninput.err,select.err,textarea.err{border-color:"+C.red+";}\nbutton{font-family:'Nunito',sans-serif;cursor:pointer;border:none;border-radius:10px;font-weight:700;transition:all .18s;-webkit-tap-highlight-color:transparent;}\nbutton:active{transform:scale(.97);}\nlabel{font-size:13px;font-weight:700;color:"+C.brownDark+";display:block;margin-bottom:5px;}\n@keyframes slideUp{from{transform:translateY(24px);opacity:0;}to{transform:translateY(0);opacity:1;}}\n@keyframes fadeIn{from{opacity:0;}to{opacity:1;}}";};
function simEmail(email,subject,push){push("Email -> "+(email||"?")+" : "+subject,"success");}
function simWA(phone,msg,push){if(phone)push("WhatsApp -> "+phone+" : "+msg.slice(0,40),"success");}